# Generated by Django 5.1.1 on 2024-10-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="amount",
            field=models.IntegerField(default=150),
        ),
    ]
